import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import MobileFooter from "@/components/mobile-footer";
import MobileHeader from "@/components/mobile-header";
import Sidebar from "@/components/sidebar";
import SuggestionBar from "@/components/suggestions";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Home / X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased relative max-w-[1400px] mx-auto",
          ubuntu.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex relative">
            <Sidebar />
            <div className="flex-1 border-x-2 h-[2000px] relative">
              <MobileHeader />
              {children}
              <MobileFooter />
            </div>
            <SuggestionBar />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
