import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import MobileFooter from "@/components/footer/mobile-footer";
import Sidebar from "@/components/sidebar/sidebar";
import SuggestionBar from "@/components/suggestions/suggestions";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Home / X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased relative max-w-[1300px] mx-auto",
          ubuntu.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex relative">
            <Sidebar />
            <div className="flex-1 border-x-2">
              {children}
              <MobileFooter />
            </div>
            <SuggestionBar />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
